### ISSUE TITLE
一些怪怪的报错

### ISSUE THREAD

**Issue by greenhandzdl** [project-mirai/chat-command#11]
![Screenshot_20220129_144003_io github mzdluo123 mirai android](https://user-images.githubusercontent.com/61241103/151650832-bea3c4db-bd2c-42f9-bd53-c7e2cb45af53.jpg)
该插件无法正常工作，如发送回该群（另外我是被给予的＊权限，铁定不是权限问题）

**Comment by Karlatemp** [comment]
`发送消息` 被其他插件给拦截了，请自行排查是哪个插件拦截的，与 chat-command 无关

**Comment by greenhandzdl** [comment]
感谢
