### ISSUE TITLE
什么时候同步到jcenter呢

### ISSUE THREAD

**Issue by EzraRT** [project-mirai/chat-command#22]
Hi，0.6.0也发布了，什么时候发布到jcenter呢。

**Comment by Him188** [comment]
你指的可能是 Maven Central

**Comment by EzraRT** [comment]
在 https://developer.aliyun.com/artifact/aliyunMaven/searchArtifactByWords?repoId=all&queryTerm=chat-command&_input_charset=utf-8 查询到它发布在jcenter仓库，请问什么时候提交0.6.0版本更新呢。
